dist: trusty
language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
install: 
- npm i npmci
before_script:
- npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &
script:
- npx cypress run
deploy:
  provider: surge
  skip_cleanup: true
  domain: mymovie.surge.sh
  project: ./dist
  on:
    branch: master


